export const cars = [
  // ALFA ROMEO
  {
    brand: "Alfa Romeo",
    model: "Stelvio Quadrifolgio",
    productionYear: 2018,
    originCountry: "Italy",
    engine: {
      type: "V6",
      capacity: "2.9L",
      hp: 506,
      nm: 599,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "8-speed",
    weight: "1978kg",
    image: "Stelvio-Quadrifolgio.png",
  },
  {
    brand: "Alfa Romeo",
    model: "Giulia Quadrifolgio",
    productionYear: 2017,
    originCountry: "Italy",
    engine: {
      type: "V6",
      capacity: "2.9L",
      hp: 506,
      nm: 600,
    },
    enginePos: "front",
    drive: "rear",
    transimssion: "6-speed",
    weight: "1524kg",
    image: "Giulia-Quadrifolgio.png",
  },
  // ASTON MARTIN
  {
    brand: "Aston Martin",
    model: "DBS Superleggera",
    productionYear: 2019,
    originCountry: "United Kingdom",
    engine: {
      type: "V12",
      capacity: "5.2L",
      hp: 715,
      nm: 899,
    },
    enginePos: "front",
    drive: "rear",
    transimssion: "8-speed",
    weight: "1799kg",
    image: "DBS-Superleggera.png",
  },
  {
    brand: "Aston Martin",
    model: "DBX",
    productionYear: 2021,
    originCountry: "United Kingdom",
    engine: {
      type: "V8",
      capacity: "4.0L",
      hp: 543,
      nm: 700,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "9-speed",
    weight: "2245kg",
    image: "DBX.png",
  },
  {
    brand: "Aston Martin",
    model: "VALKYRIE",
    productionYear: 2023,
    originCountry: "United Kingdom",
    engine: {
      type: "V12",
      capacity: "6.5L",
      hp: 1140,
      nm: 899,
    },
    enginePos: "mid",
    drive: "rear",
    transimssion: "7-speed",
    weight: "1350kg",
    image: "Valykrie.png",
  },
  // AUDI
  {
    brand: "Audi",
    model: "R8 V10 Plus",
    productionYear: 2016,
    originCountry: "Germany",
    engine: {
      type: "V10",
      capacity: "5.2L",
      hp: 602,
      nm: 560,
    },
    enginePos: "mid",
    drive: "all",
    transimssion: "7-speed",
    weight: "1555kg",
    image: "R8-V10-Plus.png",
  },
  {
    brand: "Audi",
    model: "RS3",
    productionYear: 2020,
    originCountry: "Germany",
    engine: {
      type: "I5",
      capacity: "2.5L",
      hp: 394,
      nm: 480,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "7-speed",
    weight: "1630kg",
    image: "RS3.png",
  },
  {
    brand: "Audi",
    model: "RS4 Avant",
    productionYear: 2018,
    originCountry: "Germany",
    engine: {
      type: "V6",
      capacity: "2.9L",
      hp: 444,
      nm: 599,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "8-speed",
    weight: "1790kg",
    image: "RS4-Avant.png",
  },
  {
    brand: "Audi",
    model: "RS6 Avant",
    productionYear: 2021,
    originCountry: "Germany",
    engine: {
      type: "V8",
      capacity: "4.0L",
      hp: 591,
      nm: 800,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "8-speed",
    weight: "2075kg",
    image: "RS6-Avant.png",
  },
  {
    brand: "Audi",
    model: "RS E-Tron GT",
    productionYear: 2021,
    originCountry: "Germany",
    engine: {
      type: "Electric Motors",
      capacity: "2x",
      hp: 637,
      nm: 830,
    },
    enginePos: "mid",
    drive: "all",
    transimssion: "2-speed",
    weight: "2347kg",
    image: "RS-E-Tron-GT.png",
  },
  {
    brand: "Audi",
    model: "TT RS",
    productionYear: 2018,
    originCountry: "Germany",
    engine: {
      type: "I5",
      capacity: "2.5L",
      hp: 400,
      nm: 480,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "7-speed",
    weight: "1500kg",
    image: "TT-RS.png",
  },
  // BMW
  {
    brand: "BMW",
    model: "M2",
    productionYear: 2023,
    originCountry: "Germany",
    engine: {
      type: "I6",
      capacity: "3.0L",
      hp: 453,
      nm: 405,
    },
    enginePos: "front",
    drive: "rear",
    transimssion: "6-speed",
    weight: "1700kg",
    image: "M2-2023.png",
  },
  {
    brand: "BMW",
    model: "M2",
    productionYear: 2016,
    originCountry: "Germany",
    engine: {
      type: "I6",
      capacity: "3.0L",
      hp: 365,
      nm: 369,
    },
    enginePos: "front",
    drive: "rear",
    transimssion: "6-speed",
    weight: "1565kg",
    image: "M2-2016.png",
  },
  {
    brand: "BMW",
    model: "M3 Competition",
    productionYear: 2021,
    originCountry: "Germany",
    engine: {
      type: "I6",
      capacity: "3.0L",
      hp: 503,
      nm: 649,
    },
    enginePos: "front",
    drive: "rear",
    transimssion: "8-speed",
    weight: "1730kg",
    image: "M3-Competition.png",
  },
  {
    brand: "BMW",
    model: "M4 Competition",
    productionYear: 2021,
    originCountry: "Germany",
    engine: {
      type: "I6",
      capacity: "3.0L",
      hp: 503,
      nm: 649,
    },
    enginePos: "front",
    drive: "rear",
    transimssion: "8-speed",
    weight: "1725kg",
    image: "M4-Competition.png",
  },
  {
    brand: "BMW",
    model: "M5",
    productionYear: 2018,
    originCountry: "Germany",
    engine: {
      type: "V8",
      capacity: "4.4L",
      hp: 599,
      nm: 750,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "8-speed",
    weight: "1982kg",
    image: "M5.png",
  },
  {
    brand: "BMW",
    model: "M8 Competition",
    productionYear: 2020,
    originCountry: "Germany",
    engine: {
      type: "V8",
      capacity: "4.4L",
      hp: 617,
      nm: 750,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "8-speed",
    weight: "1975kg",
    image: "M8-Competition.png",
  },
  // CHEVROLET
  {
    brand: "Chevrolet",
    model: "Camaro ZL1",
    productionYear: 2017,
    originCountry: "United State of America",
    engine: {
      type: "V8",
      capacity: "6.2L",
      hp: 650,
      nm: 881,
    },
    enginePos: "front",
    drive: "rear",
    transimssion: "6-speed",
    weight: "1761kg",
    image: "Camaro-ZL1.png",
  },
  {
    brand: "Chevrolet",
    model: "Corvette Z06",
    productionYear: 2023,
    originCountry: "United State of America",
    engine: {
      type: "V8",
      capacity: "5.5L",
      hp: 670,
      nm: 624,
    },
    enginePos: "mid",
    drive: "rear",
    transimssion: "8-speed",
    weight: "1613kg",
    image: "Corvette-Z06.png",
  },
  // CUPRA
  {
    brand: "Cupra",
    model: "Formentor VZ5",
    productionYear: 2021,
    originCountry: "Spain",
    engine: {
      type: "I5",
      capacity: "2.5L",
      hp: 385,
      nm: 480,
    },
    enginePos: "front",
    drive: "all",
    transimssion: "7-speed",
    weight: "1608kg",
    image: "Formentor-VZ5.png",
  },
]
